import { from } from "rxjs";
export { ProductosCreateComponent } from "./products/productos-create/productos-create.component";
export { ProductosEditComponent } from "./products/productos-edit/productos-edit.component";
export { ProductosComponent } from "./products/productos/productos.component";
export { ModeloproductosCreateComponent } from "./models-products/modeloproductos-create/modeloproductos-create.component";
export { ModeloproductosEditComponent } from "./models-products/modeloproductos-edit/modeloproductos-edit.component";
export { ModeloproductosComponent } from "./models-products/modeloproductos/modeloproductos.component";
export { AtributosCreateComponent } from "./attributes/atributos-create/atributos-create.component";
export { AtributosEditComponent } from "./attributes/atributos-edit/atributos-edit.component";
export { AtributosComponent } from "./attributes/atributos/atributos.component";
export { ColorsCreateComponent } from "./colors/colors-create/colors-create.component";
export { ColorsEditComponent } from "./colors/colors-edit/colors-edit.component";
export { ColorsComponent } from "./colors/colors/colors.component";
export { GenerosCreateComponent } from "./genres/generos-create/generos-create.component";
export { GenerosEditComponent } from "./genres/generos-edit/generos-edit.component";
export { GenerosComponent } from "./genres/generos/generos.component";
export { MarcasCreateComponent } from "./marks/marcas-create/marcas-create.component";
export { MarcasEditComponent } from "./marks/marcas-edit/marcas-edit.component";
export { MarcasComponent } from "./marks/marcas/marcas.component";
export { ModelosCreateComponent } from "./models/modelos-create/modelos-create.component";
export { ModelosEditComponent } from "./models/modelos-edit/modelos-edit.component";
export { ModelosComponent } from "./models/modelos/modelos.component";
export { SociedadesEditComponent } from "./corporations/sociedades-edit/sociedades-edit.component";
export { SociedadesComponent } from "./corporations/sociedades/sociedades.component";
export { DashboardAdmComponent } from "./dashboard-adm/dashboard-adm.component";
export { DashboardClComponent } from "./dashboard-cl/dashboard-cl.component";
export { GruposCreateComponent } from "./groups/grupos-create/grupos-create.component";
export { GruposEditComponent } from "./groups/grupos-edit/grupos-edit.component";
export { GruposComponent } from "./groups/grupos/grupos.component";
export { NavegationAdmComponent } from "./navegation-adm/navegation-adm.component";
export { NavegationClComponent } from "./navegation-cl/navegation-cl.component";
export { AlmacenesCreateComponent } from "./warehouses/almacenes-create/almacenes-create.component";
export { AlmacenesEditComponent } from "./warehouses/almacenes-edit/almacenes-edit.component";
export { AlmacenesComponent } from "./warehouses/almacenes/almacenes.component";
export { AlmacenessociedadCreateComponent } from "./warehouses/almacenessociedad-create/almacenessociedad-create.component";
export { AlmacenessociedadEditComponent } from "./warehouses/almacenessociedad-edit/almacenessociedad-edit.component";
export { AlmacenessociedadComponent } from "./warehouses/almacenessociedad/almacenessociedad.component";
export { CategoriasCreateComponent } from "./categories/categorias-create/categorias-create.component";
export { CategoriasEditComponent } from "./categories/categorias-edit/categorias-edit.component";
export { CategoriasComponent } from "./categories/categorias/categorias.component";
export { SociedadesCreateComponent } from "./corporations/sociedades-create/sociedades-create.component";
export { LineasCreateComponent } from "./lines/lineas-create/lineas-create.component";
export { LineasEditComponent } from "./lines/lineas-edit/lineas-edit.component";
export { LineasComponent } from "./lines/lineas/lineas.component";
export { InventariosComponent } from "./inventories/inventarios/inventarios.component";
export { InventariosPedidoComponent } from "./inventories/inventarios-pedido/inventarios-pedido.component";
export { InventariosPedidoColoresComponent } from "./inventories/inventarios-pedido-colores/inventarios-pedido-colores.component";
export { InventariosPedidoLineasComponent } from "./inventories/inventarios-pedido-lineas/inventarios-pedido-lineas.component";
export { InventariosPedidoModelosComponent } from "./inventories/inventarios-pedido-modelos/inventarios-pedido-modelos.component";
export { InventariosPedidoCategoriaComponent } from "./inventories/inventarios-pedido-categoria/inventarios-pedido-categoria.component";
export { PedidoSugeridoComponent } from "./orders/pedido-sugerido/pedido-sugerido.component";
export { DashboardBoComponent} from "./dashboard-bo/dashboard-bo.component";
export { NavegationBoComponent} from "./navegation-bo/navegation-bo.component";
export { InventariosAlmacenComponent} from "./inventories/inventarios-almacen/inventarios-almacen.component";
export { InventariosProductosComponent} from "./inventories/inventarios-productos/inventarios-productos.component";
export { UsuarioComponent} from "./users/usuario/usuario.component";
export { UsuarioPassComponent} from "./users/usuario-pass/usuario-pass.component";
export { CatalogosComponent} from "./inventories/catalogos/catalogos.component";
export { TercerosComponent} from "./users/terceros/terceros.component";
export { TercerosCreateComponent} from "./users/terceros-create/terceros-create.component";
export { TercerosalmacenComponent} from "./users/tercerosalmacen/tercerosalmacen.component";
export { TercerosusuariosComponent} from "./users/tercerosusuarios/tercerosusuarios.component";
export { TercerosusuariosCreateComponent} from "./users/tercerosusuarios-create/tercerosusuarios-create.component";
export { TercerosusuariosEditComponent} from "./users/tercerosusuarios-edit/tercerosusuarios-edit.component";